fixing cicd

diff --git a/.github/workflows/test-main-branch.yml b/.github/workflows/test-main-branch.yml
--- a/.github/workflows/test-main-branch.yml
+++ b/.github/workflows/test-main-branch.yml
@@ -1,8 +1,8 @@
-name: Test pull request to main branch
+name: Laravel
 
 on:
   pull_request:
-    branches: [ "main" ]
+    branches: ["main"]
 
 jobs:
   laravel-tests:
@@ -25,41 +25,52 @@ jobs:
           --health-retries=5
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Set up PHP
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: '8.1'
-    - name: Copy .env.testing to .env
-      run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
-    - name: Install Dependencies
-      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
-    - name: Generate key
-      run: php artisan key:generate
-    - name: Directory Permissions
-      run: chmod -R 777 storage bootstrap/cache
-    - name: Wait for MySQL to be ready
-      run: |
-        sleep 30
-        while ! mysqladmin ping -h"127.0.0.1" --silent; do
-          echo "Waiting for database connection..."
-          sleep 5
-        done
-    - name: Prepare Database
-      run: php artisan migrate
-      env:
-        DB_CONNECTION: mysql
-        DB_HOST: 127.0.0.1
-        DB_PORT: 3306
-        DB_DATABASE: productize_test
-        DB_USERNAME: test
-        DB_PASSWORD: 123456
-    - name: Execute tests (Unit and Feature tests) via PHPUnit
-      run: php artisan test
-      env:
-        DB_CONNECTION: mysql
-        DB_HOST: 127.0.0.1
-        DB_PORT: 3306
-        DB_DATABASE: productize_test
-        DB_USERNAME: test
-        DB_PASSWORD: 123456
+      - uses: actions/checkout@v3
+      - name: Set up PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: "8.1"
+      - name: Copy .env.testing to .env
+        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
+      - name: Install Dependencies
+        run: |
+          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
+          echo $? # Output exit code
+      - name: Generate key
+        run: |
+          php artisan key:generate
+          echo $? # Output exit code
+      - name: Directory Permissions
+        run: |
+          chmod -R 777 storage bootstrap/cache
+          echo $? # Output exit code
+      - name: Wait for MySQL to be ready
+        run: |
+          sleep 30
+          while ! mysqladmin ping -h"127.0.0.1" --silent; do
+            echo "Waiting for database connection..."
+            sleep 5
+          done
+          echo $? # Output exit code
+      - name: Prepare Database
+        run: |
+          php artisan migrate
+          echo $? # Output exit code
+        env:
+          DB_CONNECTION: mysql
+          DB_HOST: 127.0.0.1
+          DB_PORT: 3306
+          DB_DATABASE: productize_test
+          DB_USERNAME: test
+          DB_PASSWORD: 123456
+      - name: Execute tests (Unit and Feature tests) via PHPUnit
+        run: |
+          php artisan test
+          echo $? # Output exit code
+        env:
+          DB_CONNECTION: mysql
+          DB_HOST: 127.0.0.1
+          DB_PORT: 3306
+          DB_DATABASE: productize_test
+          DB_USERNAME: test
+          DB_PASSWORD: 123456
